version: '3.4'

services:
  servicecatalogdb:
    container_name: servicecatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cartdb:
    container_name: cartdb
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  servicecatalog.api:
    container_name: servicecatalog.api
    depends_on:
      - servicecatalogdb
    ports:
      - "8000:80"
      - "9099:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://servicecatalogdb:27017"
      - "Kestrel:Endpoints:webApi:Protocols=Http1"
      - "Kestrel:Endpoints:webApi:Url=http://servicecatalog.api:80"
      - "Kestrel:Endpoints:Grpc:Protocols=Http2"
      - "Kestrel:Endpoints:Grpc:Url=http://servicecatalog.api:443"

  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cartdb:6379"
      - "GrpcSettings:CatalogUrl=http://servicecatalog.api:443"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - cartdb
      - rabbitmq
    ports:
      - "8001:80"

  ordering.api:
    container_name: ordering.api
    ports:
      - "8002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - servicecatalog.api
        - cart.api
        - ordering.api
    ports:
      - "8010:80"
