version: '3.4'

services:
  servicecatalogdb:
    container_name: servicecatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cartdb:
    container_name: cartdb
    restart: always
    ports:
      - "6379:6379"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  servicecatalog.api:
    container_name: servicecatalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://servicecatalogdb:27017"
      - "Kestrel:Endpoints:webApi:Protocols=Http1"
      - "Kestrel:Endpoints:webApi:Url=http://servicecatalog.api:8000"
      - "Kestrel:Endpoints:Grpc:Protocols=Http1"
      - "Kestrel:Endpoints:Grpc:Url=http://servicecatalog.api:9099"
    depends_on:
      - servicecatalogdb
    ports:
      - "8000:80"
      - "9099:443"

  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cartdb:6379"
      - "GrpcSettings:CatalogUrl=http://servicecatalog.api:9099"
    depends_on:
      - cartdb
    ports:
      - "8001:80"
