version: '3.4'

services:

  consul-client:
    container_name: consul-client
    restart: always
    volumes:
     - ./ApiGateways/OcelotApiGw/consul/client.json:/consul/config/client.json:ro
    networks:
      - consul
    command: "agent"

  consul-server:
    container_name: consul-server
    restart: always
    hostname: service-registry
    volumes:
     - ./ApiGateways/OcelotApiGw/consul/server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"  

  servicecatalogdb:
    container_name: servicecatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cartdb:
    container_name: cartdb
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    networks:
      - consul
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  ocelotapigw:
    container_name: ocelotapigw
    networks:
      - consul
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - servicecatalog.api
        - cart.api
        - ordering.api
        - consul-server
    ports:
      - "8010:80"

  servicecatalog.api:
    container_name: servicecatalog.api
    hostname: servicecatalogApi
    networks:
      - consul
    depends_on:
      - servicecatalogdb
      - consul-server
    ports:
      - "8000:80"
      - "9099:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://servicecatalogdb:27017"
      - "Kestrel:Endpoints:webApi:Protocols=Http1"
      - "Kestrel:Endpoints:webApi:Url=http://servicecatalog.api:80"
      - "Kestrel:Endpoints:Grpc:Protocols=Http2"
      - "Kestrel:Endpoints:Grpc:Url=http://servicecatalog.api:443"
      - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
      - ServiceConfig__ServiceAddress=http://servicecatalogApi

  cart.api:
    container_name: cart.api
    hostname: cartApi
    networks:
      - consul
    depends_on:
      - cartdb
      - rabbitmq
      - consul-server
    ports:
      - "8001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cartdb:6379"
      - "GrpcSettings:CatalogUrl=http://servicecatalog.api:443"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
      - ServiceConfig__ServiceAddress=http://cartApi

  ordering.api:
    container_name: ordering.api
    hostname: orderingApi
    ports:
      - "8002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
      - ServiceConfig__ServiceAddress=http://orderingApi
    depends_on:
      - rabbitmq
      - consul-server
    networks:
      - consul

  

networks:
  consul:
    driver: bridge
