version: '3.4'

services:
  servicecatalogdb:
    container_name: servicecatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cartdb:
    container_name: cartdb
    restart: always
    ports:
      - "6379:6379"

  servicecatalog.api:
    container_name: servicecatalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://servicecatalogdb:27017"
    depends_on:
      - servicecatalogdb
    ports:
      - "8000:80"

  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cartdb:6379"
    depends_on:
      - cartdb
    ports:
      - "8001:80"
